// <auto-generated />
using System;
using Mhrm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mhrm.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260912022800_InitialSqlite")]
    partial class InitialSqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Mhrm.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("HoursPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Salary")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("contracts");
                });

            modelBuilder.Entity("Mhrm.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "رسیدگی به وظایف تعیین شده مدیریت",
                            Name = "اداری"
                        },
                        new
                        {
                            Id = 2,
                            Description = "مدیر و معاونان",
                            Name = "مدیریت"
                        },
                        new
                        {
                            Id = 3,
                            Description = "کارگران خط تولید",
                            Name = "تولید"
                        });
                });

            modelBuilder.Entity("Mhrm.Models.DepartmentPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("DepartmentPosition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            PositionId = 1
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            PositionId = 2
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            PositionId = 3
                        });
                });

            modelBuilder.Entity("Mhrm.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FileType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Mhrm.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentPositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InsuranceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("National_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentPositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentPositionId = 1,
                            Email = "admin@hrm.com",
                            FirstName = "System",
                            HireDate = new DateTime(2026, 9, 12, 5, 58, 0, 20, DateTimeKind.Local).AddTicks(4676),
                            InsuranceNumber = "INS-001",
                            LastName = "Admin",
                            National_id = "1111111111",
                            Phone = "09000000000",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Mhrm.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Request_by")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Mhrm.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublishedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Content = "به سامانه مدیریت منابع انسانی خوش آمدید. این سامانه با هدف تسهیل فرآیندهای اداری، دسترسی سریع به اطلاعات کارکنان، ثبت درخواست‌ها، مشاهده اطلاعیه‌ها و بهبود ارتباطات سازمانی طراحی شده است. امیدواریم این سامانه تجربه‌ای ساده، سریع و کارآمد را برای شما فراهم کند. از همراهی و همکاری شما سپاسگزاریم و برایتان موفقیت و پیشرفت روزافزون آرزو داریم",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "/images/LOGO.jpg",
                            IsActive = true,
                            IsImportant = false,
                            PublishedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishedBy = 1,
                            Title = "خوش امدید"
                        });
                });

            modelBuilder.Entity("Mhrm.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permission_Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descriptions = "Create / Delete User",
                            Permission_Key = "Add and delete"
                        },
                        new
                        {
                            Id = 2,
                            Descriptions = "Edit User",
                            Permission_Key = "Edit"
                        },
                        new
                        {
                            Id = 3,
                            Descriptions = " Making changes to information by the employee herself",
                            Permission_Key = "Making changes"
                        });
                });

            modelBuilder.Entity("Mhrm.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "نظارت بر بخش زیر نظر مدیر",
                            Title = "کارشناس"
                        },
                        new
                        {
                            Id = 2,
                            Description = "نظارت بر بخش",
                            Title = "مدیر"
                        },
                        new
                        {
                            Id = 3,
                            Description = "کارگر",
                            Title = "اپراتور"
                        });
                });

            modelBuilder.Entity("Mhrm.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LeaveRequest")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestBy");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("Mhrm.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin*"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MHR"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 5,
                            Name = "JustSeeing"
                        });
                });

            modelBuilder.Entity("Mhrm.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("permission_sid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("roles_permissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        });
                });

            modelBuilder.Entity("Mhrm.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("EmployeeId1")
                        .IsUnique();

                    b.ToTable("Tab_User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "System Administrator",
                            EmployeeId = 1,
                            Password = "123",
                            RoleId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Mhrm.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Expirees_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip_address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Login_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Logout_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("Session_token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User_agent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Mhrm.Models.Contract", b =>
                {
                    b.HasOne("Mhrm.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mhrm.Models.DepartmentPosition", b =>
                {
                    b.HasOne("Mhrm.Models.Department", "Department")
                        .WithMany("DepartmentPosition")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mhrm.Models.Position", "Position")
                        .WithMany("DepartmentPosition")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Mhrm.Models.Document", b =>
                {
                    b.HasOne("Mhrm.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Mhrm.Models.Employee", b =>
                {
                    b.HasOne("Mhrm.Models.DepartmentPosition", "DepartmentPosition")
                        .WithMany()
                        .HasForeignKey("DepartmentPositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentPosition");
                });

            modelBuilder.Entity("Mhrm.Models.Request", b =>
                {
                    b.HasOne("Mhrm.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mhrm.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("RequestBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mhrm.Models.RolePermission", b =>
                {
                    b.HasOne("Mhrm.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mhrm.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Mhrm.Models.User", b =>
                {
                    b.HasOne("Mhrm.Models.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("Mhrm.Models.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mhrm.Models.Employee", null)
                        .WithOne("User")
                        .HasForeignKey("Mhrm.Models.User", "EmployeeId1");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Mhrm.Models.UserSession", b =>
                {
                    b.HasOne("Mhrm.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mhrm.Models.Department", b =>
                {
                    b.Navigation("DepartmentPosition");
                });

            modelBuilder.Entity("Mhrm.Models.Employee", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Mhrm.Models.Position", b =>
                {
                    b.Navigation("DepartmentPosition");
                });
#pragma warning restore 612, 618
        }
    }
}
